// ============================================================
//  WEB ENGINEERING KLAUSUR-TRAINER — DATA
//  Alle Lerninhalte basierend auf den Vorlesungsfolien T0–T6,
//  Altklausuren, WEBFragen.pdf und dem MongoDB Workshop.
// ============================================================

const TOPICS = [
    { id:"js-es6", title:"Modernes JavaScript (ES6) & Variablen", priority:"high",
      explanation:"ES6 brachte let/const (Block Scope), Arrow Functions, Promises, Klassen (syntaktischer Zucker über Prototypen), Template Literals, Destructuring und Module. Primitive Typen (string, number, boolean, null, undefined, symbol, bigint) sind immutable. Bei Objekten wird nur die Referenz kopiert.",
      keyPoints:["let & const statt var (Block Scope)","Primitive = immutable, Objekte = Referenz","Klassen = syntaktischer Zucker über Prototypen","Arrow Functions haben kein eigenes this"] },
    { id:"scopes", title:"Scopes: Function vs Block Scope", priority:"high",
      explanation:"var hat Function Scope und wird gehoben (hoisted → Declaration wird nach oben gezogen, Wert ist undefined). let und const haben Block Scope ({}, if, for). Implizit globale Variablen (ohne Schlüsselwort) landen im globalen Scope (window) – immer vermeiden!",
      keyPoints:["var → Function Scope + Hoisting","let/const → Block Scope, kein Hoisting","Implizit globale Variablen = Namespace-Verschmutzung","const = Referenz unveränderbar (Inhalt bei Objekten schon)"] },
    { id:"closures", title:"Closures & Arrow Functions", priority:"high",
      explanation:"Eine Closure entsteht, wenn eine innere Funktion auf Variablen der äußeren Funktion zugreift – auch nachdem die äußere Funktion bereits zurückgekehrt ist. Arrow Functions (=>) haben KEIN eigenes this – sie erben this vom umgebenden lexikalischen Scope.",
      keyPoints:["Closure = innere Funktion nutzt äußere Variable","Arrow Functions: kein eigenes this (lexikalisch)","Reguläre Funktionen: eigenes this (Aufrufkontext)","Closures ermöglichen private Variablen / State"] },
    { id:"oop", title:"OOP in JavaScript (Prototypen & Klassen)", priority:"high",
      explanation:"JavaScript verwendet prototypenbasierte Vererbung. ES6-Klassen (class, extends, constructor, super) sind reiner syntaktischer Zucker – das Prototypen-System bleibt darunter. Methoden können mit super aufgerufen und überschrieben werden.",
      keyPoints:["Prototypenbasierte Vererbung, nicht klassisch","class/extends = syntaktischer Zucker","constructor() + super() für Elternklasse","Methoden überschreiben durch gleichen Namen"] },
    { id:"async", title:"Asynchrone Programmierung & Event Loop", priority:"high",
      explanation:"JavaScript ist single-threaded (ein Call Stack). Der Event Loop ermöglicht nicht-blockierende Ausführung: Call Stack → Web APIs/libuv → Callback Queue → Event Loop prüft ob Stack leer → führt nächsten Callback aus. IO wird ans OS delegiert.",
      keyPoints:["Single-Threaded + Event Loop = nicht-blockierend","IO wird an OS/libuv delegiert","Callbacks → Promises → async/await","CPU-intensive Tasks blockieren den Event Loop!"] },
    { id:"promises", title:"Promises & async/await", priority:"high",
      explanation:"Ein Promise repräsentiert einen zukünftigen Wert. Zustände: pending → fulfilled (resolve) oder rejected (reject). .then() für Erfolg, .catch() für Fehler, .finally() läuft immer. async/await ist syntaktischer Zucker: await pausiert bis das Promise resolved.",
      keyPoints:["new Promise((resolve, reject) => { ... })",".then().catch().finally()","async function → gibt Promise zurück","await pausiert bis Promise resolved"] },
    { id:"modules", title:"Module (import/export)", priority:"medium",
      explanation:"Named Exports: export function foo() {} → import { foo } from './file.js'. Default Export: export default class → import Name from './file.js'. CommonJS (Node alt): module.exports / require().",
      keyPoints:["Named: export { foo } → import { foo }","Default: export default → import Name","CommonJS: module.exports / require()","ES Modules = moderner Standard"] },
    { id:"node", title:"Node.js & NPM", priority:"medium",
      explanation:"Node.js ist eine Open-Source JS-Laufzeitumgebung für serverseitiges JS. NPM verwaltet Abhängigkeiten. npm init -y erstellt package.json. npm install express installiert Pakete.",
      keyPoints:["JS-Laufzeitumgebung außerhalb des Browsers","Single-Threaded mit Event Loop (libuv)","npm init -y → package.json","npm install <paket> → Dependencies"] },
    { id:"rest-express", title:"REST-Architektur & Express.js", priority:"high",
      explanation:"REST = Representational State Transfer. Statelessness, Uniform Interface, Ressourcen über URIs, Repräsentationen (JSON). Express.js: Routing (app.get/post/put/delete()) + Middleware. Pfadparameter /:id vs Queryparameter ?key=value.",
      keyPoints:["Stateless, Uniform Interface, Ressourcen via URIs","GET=Read, POST=Create, PUT=Update, DELETE=Delete","Express: Routing + Middleware","Pfadparam /:id vs Query ?key=value"] },
    { id:"http", title:"HTTP, Header & URL-Encoding", priority:"medium",
      explanation:"Request-Header: Accept, Authorization (Bearer Token), Cookie, Content-Type. Response-Header: Set-Cookie, Allow. Statuscodes: 2xx Erfolg, 4xx Client Error, 5xx Server Error. URL-Encoding: Sonderzeichen als %+Hex.",
      keyPoints:["Request: Accept, Authorization, Cookie","Response: Set-Cookie, Allow","200 OK, 201 Created, 401, 404, 500","URL-Encoding: Sonderzeichen = %HexCode"] },
    { id:"architekturen", title:"Architekturen (Monolith vs SOA)", priority:"medium",
      explanation:"Monolith: Alles in einem Prozess – einfach zu entwickeln/deployen, aber schwer skalierbar, Single Point of Failure. SOA: Unabhängige Services über definierte Schnittstellen. Vorteile: Skalierbarkeit, unabhängiges Deployment, Technology-Freiheit.",
      keyPoints:["Monolith: einfach, aber Single Point of Failure","SOA: unabhängige Services, skalierbar","Client-Server: klare Trennung","Layer: Presentation → Business → Persistence → Data"] },
    { id:"cors", title:"CORS (Cross-Origin Resource Sharing)", priority:"medium",
      explanation:"Same-Origin-Policy: Browser blockiert Requests an andere Origins. CORS erlaubt kontrollierte Cross-Origin-Zugriffe. Server setzt Access-Control-Allow-Origin. Bei PUT/DELETE/custom Headers: Preflight-Request (OPTIONS).",
      keyPoints:["Same-Origin: gleiches Protocol+Domain+Port","Server: Access-Control-Allow-Origin","Preflight (OPTIONS) bei PUT/DELETE","CORS wird im Browser enforced"] },
    { id:"vue", title:"Vue.js, MVVM & AJAX", priority:"high",
      explanation:"MVVM: Model (Daten) – View (HTML) – ViewModel (Vue). v-model (Two-Way), v-bind/{{ }} (One-Way), v-if/v-show, v-for. Lifecycle Hooks: created, mounted, unmounted. AJAX/fetch(): Daten laden ohne Page Reload.",
      keyPoints:["MVVM: Model-View-ViewModel","v-model, v-bind, v-for, v-if","Lifecycle: created, mounted, unmounted","fetch(): async Daten laden ohne Reload"] },
    { id:"bootstrap", title:"Bootstrap (CSS Framework)", priority:"medium",
      explanation:"12-Spalten Grid-System. Breakpoints: sm, md, lg, xl, xxl. Einbindung via CDN oder npm. Statische Komponenten (CSS): Tabellen, Cards, Badges. Dynamische (+JS): Modals, Carousels, Dropdowns.",
      keyPoints:["12-Spalten Grid: col-12, col-lg-4","Breakpoints: sm, md, lg, xl, xxl","CDN oder npm install bootstrap","Statisch: Cards, Badges | Dynamisch: Modals"] },
    { id:"cookies", title:"Cookies, Sessions & State Management", priority:"high",
      explanation:"HTTP ist stateless. Cookies = Key-Value-Paare via Set-Cookie Header. Session Cookies (ohne Max-Age) vs Persistent Cookies (mit Max-Age). Wichtige Attribute: HttpOnly, Secure, SameSite, Path, Domain.",
      keyPoints:["Set-Cookie (Server→Client), Cookie (Client→Server)","Session vs Persistent Cookie","HttpOnly, Secure, SameSite=Strict/Lax","cookie-parser Middleware in Express"] },
    { id:"jwt", title:"JSON Web Tokens (JWT)", priority:"high",
      explanation:"Header.Payload.Signature (Base64). Signature = HMACSHA256(Base64(H)+'.'+Base64(P), secret). Signiert aber NICHT verschlüsselt! Authorization Header: Bearer <token>. Stateless, kein Server-State nötig.",
      keyPoints:["Aufbau: xxxxx.yyyyy.zzzzz","Signatur: HMAC(B64(H)+'.'+B64(P), secret)","Signiert ≠ verschlüsselt","Authorization: Bearer <token>"] },
    { id:"security", title:"Web-Security: SQLi, XSS, CSRF", priority:"high",
      explanation:"SQLi: Schädlicher SQL in Inputs → Prepared Statements. XSS: Böswilliges JS in Webseiten → Output Escaping + CSP. CSRF: Gefälschte Requests → SameSite-Cookies + CSRF-Tokens. OWASP Top 10 kennen.",
      keyPoints:["SQLi → Prepared Statements","XSS → Escaping + CSP","CSRF → SameSite + Token","OWASP Top 10 (A01–A10)"] },
    { id:"https", title:"HTTPS, TLS & Verschlüsselung", priority:"high",
      explanation:"Symmetrisch: gleicher Key (AES, schnell). Asymmetrisch: Public/Private Key (RSA, langsam). TLS: asymmetrisch für Handshake, symmetrisch für Daten. Zertifikate: CSR → CA → signiertes Zertifikat. Private Key NIEMALS weitergeben!",
      keyPoints:["Symmetrisch: gleicher Key, schnell","Asymmetrisch: Public/Private Key, langsam","TLS: Hybrid aus beidem","CSR → CA → Zertifikat"] },
    { id:"mongodb", title:"MongoDB & NoSQL vs SQL", priority:"medium",
      explanation:"Dokumentenorientiert (BSON), flexible Schemas. CRUD: insertOne, find, updateOne, deleteOne. SQL: Relational, Joins, ACID. NoSQL: Schemafrei, Sharding, BASE, verschiedene Typen (Key-Value, Dokument, Graph).",
      keyPoints:["BSON-Dokumente, flexible Schemas","insertOne, find, updateOne, deleteOne","SQL: ACID, Joins | NoSQL: BASE, Sharding","Node.js MongoDB Driver"] },
    { id:"tools", title:"REST-Testing & XML", priority:"medium",
      explanation:"Postman (GUI), curl (CLI), Swagger UI (Browser). XML = Extensible Markup Language – strukturiert wie JSON aber mit Tags. JSON ist Standard für Web-APIs.",
      keyPoints:["Postman, curl, Swagger UI","XML = Extensible Markup Language","JSON vs XML","fetch() für REST-Calls"] }
];

const QUESTIONS = [
    { id:"q1", text:"Was sind var, let und const? Wann sind die jeweiligen zu präferieren?", points:4, topic:"js-es6",
      answer:"<strong>var:</strong> Function Scope, Hoisting. Kann re-deklariert werden.<br><br><strong>let:</strong> Block Scope, kein Hoisting. Kann reassigned werden.<br><br><strong>const:</strong> Block Scope, muss initialisiert werden. Referenz unveränderbar (Inhalt bei Objekten schon!).<br><br><strong>Empfehlung:</strong> Immer const, let wenn Reassignment nötig. var nie verwenden." },
    { id:"q2", text:"Was sind Funktions- und Blockscopes? Worin unterscheiden sie sich?", points:4, topic:"scopes",
      answer:"<strong>Function Scope (var):</strong> Variable in der gesamten Funktion sichtbar, auch vor Deklaration (Hoisting, Wert = undefined).<br><br><strong>Block Scope (let/const):</strong> Nur innerhalb des Blocks <code>{}</code> sichtbar.<br><br>Block Scope verhindert Fehler in for-Schleifen mit setTimeout." },
    { id:"q3", text:"Was sind „Implizit Globale Variablen"? Warum vermeiden?", points:2, topic:"scopes",
      answer:"Entstehen ohne var/let/const. Landen im globalen Scope (window).<br><br><strong>Vermeiden weil:</strong> Namespace-Verschmutzung, schwer lesbar, Seiteneffekte, 'use strict' wirft Fehler." },
    { id:"q4", text:"Wie wird Speicher in JavaScript verwaltet?", points:4, topic:"js-es6",
      answer:"Automatische Speicherverwaltung durch <strong>Garbage Collector</strong>.<br><br>1. <strong>Reservieren</strong> bei Deklaration<br>2. <strong>Verwenden</strong> (lesen/schreiben)<br>3. <strong>Freigeben</strong> wenn keine Referenzen mehr<br><br>Memory Leaks vermeiden: Event Listener entfernen, globale Variablen minimieren." },
    { id:"q5", text:"Welches Prinzip liegt hinter dem OOP-Konzept von JavaScript?", points:4, topic:"oop",
      answer:"<strong>Prototypenbasierte Vererbung.</strong> Objekte erben direkt von anderen Objekten über die Prototype Chain.<br><br>ES6-Klassen sind <strong>syntaktischer Zucker</strong> – Prototypen-System bleibt darunter." },
    { id:"q6", text:"Erstellen Sie Klasse Tier (2 Attribute, 1 Methode). Leiten Sie Hund ab, überschreiben Sie die Methode.", points:6, topic:"oop",
      answer:"<pre class='code-block'><span class='kw'>class</span> Tier {\n  constructor(name, alter) {\n    this.name = name;\n    this.alter = alter;\n  }\n  sprich() {\n    return `${this.name} macht ein Geräusch`;\n  }\n}\n\n<span class='kw'>class</span> Hund <span class='kw'>extends</span> Tier {\n  constructor(name, alter, rasse) {\n    <span class='kw'>super</span>(name, alter);\n    this.rasse = rasse;\n  }\n  sprich() {\n    return `${this.name} bellt: Wuff!`;\n  }\n}\n\nconst tier = new Tier('Katze', 3);\nconst hund = new Hund('Rex', 5, 'Schäferhund');</pre>" },
    { id:"q7", text:"Was ist asynchrone Programmierung? Single- oder multi-threaded in JS?", points:4, topic:"async",
      answer:"<strong>Synchron:</strong> Sequenziell, blockierend.<br><strong>Asynchron:</strong> Nicht-blockierend, Tasks können parallel gestartet werden.<br><br>JavaScript ist <strong>single-threaded</strong>. Der Event Loop mit Callback Queue ermöglicht nicht-blockierende Ausführung. IO wird an OS/libuv delegiert." },
    { id:"q8", text:"Erklären Sie den Event Loop. Warum kann Node.js trotz Single-Threading tausende Verbindungen bedienen?", points:8, topic:"async",
      answer:"1. Code im <strong>Call Stack</strong><br>2. Async-Ops an <strong>Web APIs/libuv</strong> delegiert<br>3. Callback in <strong>Callback Queue</strong><br>4. Event Loop: Stack leer? → nächster Callback<br><br><strong>Warum tausende?</strong> IO blockiert nicht – läuft im OS. Nur CPU-intensive Tasks blockieren." },
    { id:"q9", text:"Erstellen Sie ein Promise (nach 1 Min Zufallszahl). Verknüpfen Sie Ausgabe-Funktion.", points:8, topic:"promises",
      answer:"<pre class='code-block'>const myPromise = new Promise((resolve, reject) => {\n  setTimeout(() => {\n    resolve(Math.random());\n  }, 60000);\n});\n\nmyPromise.then((ergebnis) => {\n  console.log('Zufallszahl:', ergebnis);\n});</pre>" },
    { id:"q10", text:"Zwei syntaktisch unterschiedliche Beispiele für Promise-Erstellung.", points:4, topic:"promises",
      answer:"<strong>1. Promise-Konstruktor:</strong><pre class='code-block'>const p = new Promise((resolve, reject) => {\n  resolve('Erfolg');\n});</pre><strong>2. Funktion die Promise zurückgibt:</strong><pre class='code-block'>function getData() {\n  return new Promise((resolve) => {\n    resolve('Daten');\n  });\n}</pre>" },
    { id:"q11", text:"whoAmI.getName() vs whoAmI.get_name() — reguläre vs Arrow Function mit this?", points:4, topic:"closures",
      answer:"<strong>getName()</strong> (regulär) → <code>'Gerhard'</code> — this = das aufrufende Objekt.<br><br><strong>get_name()</strong> (Arrow) → <code>undefined</code> — Arrow hat kein eigenes this, erbt vom äußeren Scope (global)." },
    { id:"q12", text:"Wofür steht REST? Zwei Eigenschaften + CRUD → HTTP-Methoden.", points:10, topic:"rest-express",
      answer:"<strong>REST = Representational State Transfer</strong><br><br>1. <strong>Statelessness:</strong> Jeder Request enthält alle Infos.<br>2. <strong>Uniform Interface:</strong> Standardisierte HTTP-Methoden.<br><br>Create → POST<br>Read → GET<br>Update → PUT/PATCH<br>Delete → DELETE" },
    { id:"q13", text:"Express.js Server mit GET '/api/hello' der 'Hallo' zurückgibt.", points:4, topic:"rest-express",
      answer:"<pre class='code-block'>const express = require('express');\nconst app = express();\n\napp.get('/api/hello', (req, res) => {\n  res.send('Hallo');\n});\n\napp.listen(3000);</pre>" },
    { id:"q14", text:"Express: GET '/api/login' setzt Cookie. GET '/api/secret' prüft Cookie, sonst 401.", points:6, topic:"cookies",
      answer:"<pre class='code-block'>const express = require('express');\nconst cookieParser = require('cookie-parser');\nconst app = express();\napp.use(cookieParser());\n\napp.get('/api/login', (req, res) => {\n  res.cookie('loggedin', 'true', {\n    httpOnly: true, secure: true\n  });\n  res.send('Login OK');\n});\n\napp.get('/api/secret', (req, res) => {\n  if (req.cookies.loggedin === 'true')\n    res.send('Geheimnis!');\n  else\n    res.status(401).send('unauthorized');\n});</pre>" },
    { id:"q15", text:"Wie teilt Server dem Client mit, ein Cookie zu setzen? Wie schickt Browser es zurück?", points:4, topic:"cookies",
      answer:"<strong>Server→Client:</strong> <code>Set-Cookie: name=wert; HttpOnly; Secure; SameSite=Strict; Max-Age=3600</code><br><br><strong>Client→Server:</strong> Browser sendet automatisch <code>Cookie: name=wert</code> bei passenden Requests." },
    { id:"q16", text:"Cookie-Attribute HttpOnly, Secure, SameSite=Strict — welchen Schutz?", points:6, topic:"cookies",
      answer:"<strong>HttpOnly:</strong> Kein JS-Zugriff (document.cookie) → Schutz vor XSS<br><strong>Secure:</strong> Nur HTTPS → Schutz vor MitM<br><strong>SameSite=Strict:</strong> Nur Same-Site Requests → Schutz vor CSRF" },
    { id:"q17", text:"Welche Cookie-Arten gibt es? Welche Flags erhöhen Sicherheit?", points:4, topic:"cookies",
      answer:"<strong>Session Cookies:</strong> Gelöscht bei Browser-Schließung.<br><strong>Persistent Cookies:</strong> Bleiben bis Max-Age abläuft.<br><br>Flags: Secure, HttpOnly, SameSite (Strict am sichersten)." },
    { id:"q18", text:"JWT-Token erstellen: Header h, Payload p, Secret s, HS512. Funktionen: HMACSHA512(), base64UrlEncode().", points:8, topic:"jwt",
      answer:"<pre class='code-block'>const encodedHeader = base64UrlEncode(\n  JSON.stringify(h)\n);\nconst encodedPayload = base64UrlEncode(\n  JSON.stringify(p)\n);\nconst signature = HMACSHA512(\n  encodedHeader + '.' + encodedPayload, s\n);\nconst token = encodedHeader + '.'\n  + encodedPayload + '.'\n  + signature;</pre>" },
    { id:"q19", text:"Drei typische Sicherheitsbedrohungen für Webanwendungen.", points:6, topic:"security",
      answer:"<strong>1. SQL-Injection:</strong> SQL in Inputs → Prepared Statements.<br><strong>2. XSS:</strong> Bösartiges JS in Seiten → Escaping + CSP.<br><strong>3. CSRF:</strong> Gefälschte Requests → SameSite + CSRF-Token." },
    { id:"q20", text:"SQL-Injection Attacke: GET /products/search?q=<name> mit direktem SQL.", points:6, topic:"security",
      answer:"Server: <code>SELECT * FROM products WHERE name = 'INPUT'</code><br><br><strong>Attacke:</strong> <code>?q=' OR '1'='1</code><br>→ <code>WHERE name = '' OR '1'='1'</code> → immer wahr, alle Daten.<br><br><strong>Schutz:</strong> Prepared Statements!" },
    { id:"q21", text:"Public/Private Key-Pair → gültiges Zertifikat für unbekannte Instanzen?", points:4, topic:"https",
      answer:"1. <strong>CSR erstellen</strong> mit Private Key<br>2. CSR an <strong>CA senden</strong><br>3. CA prüft, signiert, gibt <strong>Zertifikat</strong> zurück<br>4. Zertifikat auf Server installieren<br><br><strong>Private Key NIEMALS weitergeben!</strong>" },
    { id:"q22", text:"Client-Server-Architektur + Vor-/Nachteile Monolith.", points:6, topic:"architekturen",
      answer:"<strong>Client-Server:</strong> Client sendet Request → Server verarbeitet → Response.<br><br><strong>Monolith +:</strong> Einfach, atomare Transaktionen, geringe Latenz.<br><strong>Monolith −:</strong> Schwer skalierbar, langes Deployment, Technology Lock-in, Single Point of Failure." },
    { id:"q23", text:"Vue.js Lifecycle Hooks — erklären + zwei Beispiele.", points:4, topic:"vue",
      answer:"Funktionen die zu bestimmten Zeitpunkten im Vue-Lebenszyklus aufgerufen werden.<br><br><strong>created:</strong> Instanz erstellt, DOM noch nicht da. API-Calls hier.<br><strong>mounted:</strong> Instanz an DOM gehängt. DOM-Zugriff möglich." },
    { id:"q24", text:"Bootstrap: einspaltiges Design, ab Breakpoint lg fünfspaltig.", points:4, topic:"bootstrap",
      answer:"<pre class='code-block'>&lt;div class=\"container\"&gt;\n  &lt;div class=\"row\"&gt;\n    &lt;div class=\"col-12 col-lg\"&gt;1&lt;/div&gt;\n    &lt;div class=\"col-12 col-lg\"&gt;2&lt;/div&gt;\n    &lt;div class=\"col-12 col-lg\"&gt;3&lt;/div&gt;\n    &lt;div class=\"col-12 col-lg\"&gt;4&lt;/div&gt;\n    &lt;div class=\"col-12 col-lg\"&gt;5&lt;/div&gt;\n  &lt;/div&gt;\n&lt;/div&gt;</pre>" },
    { id:"q25", text:"Drei Tools um REST-Interfaces zu testen.", points:2, topic:"tools",
      answer:"<strong>1. Postman</strong> (GUI)<br><strong>2. curl</strong> (CLI)<br><strong>3. Swagger UI</strong> (Browser)" },
    { id:"q26", text:"Wofür steht XML?", points:2, topic:"tools",
      answer:"<strong>Extensible Markup Language.</strong> Strukturiertes Datenformat mit Tags. JSON ist heute Standard für Web-APIs." }
];

const FLASHCARDS = [
    { id:"fc1", front:"Was bedeutet REST?", back:"Representational State Transfer — Stateless, Uniform Interface, Ressourcen via URIs, Repräsentationen (JSON).", topic:"rest-express" },
    { id:"fc2", front:"Unterschied var vs let?", back:"var: Function Scope + Hoisting (Wert = undefined). let: Block Scope, kein Hoisting.", topic:"scopes" },
    { id:"fc3", front:"Was ist eine Closure?", back:"Eine innere Funktion, die auf Variablen der äußeren Funktion zugreift — auch nachdem die äußere Funktion zurückgekehrt ist.", topic:"closures" },
    { id:"fc4", front:"Was ist der Event Loop?", back:"Prüft ob Call Stack leer ist → nimmt nächsten Callback aus der Queue → führt ihn aus. Ermöglicht nicht-blockierendes IO trotz Single-Thread.", topic:"async" },
    { id:"fc5", front:"Was ist CORS?", back:"Cross-Origin Resource Sharing — erlaubt kontrollierte Cross-Origin-Requests. Server setzt Access-Control-Allow-Origin Header.", topic:"cors" },
    { id:"fc6", front:"Stateless bei REST bedeutet…", back:"Jeder Request enthält ALLE nötigen Informationen. Server speichert keinen Client-State zwischen Requests.", topic:"rest-express" },
    { id:"fc7", front:"4 HTTP-Methoden für CRUD?", back:"GET (Read), POST (Create), PUT (Update), DELETE (Delete)", topic:"rest-express" },
    { id:"fc8", front:"Was ist XSS?", back:"Cross-Site Scripting — bösartiges JavaScript wird in vertrauenswürdige Webseite eingeschleust. Schutz: Output Escaping + CSP.", topic:"security" },
    { id:"fc9", front:"Was ist CSRF?", back:"Cross-Site Request Forgery — gefälschte Requests mit gültiger Authentifizierung. Schutz: SameSite-Cookies + CSRF-Token.", topic:"security" },
    { id:"fc10", front:"Was ist SQL Injection?", back:"Einschleusen von schädlichem SQL-Code in Eingabefelder/URL-Parameter. Schutz: Prepared Statements.", topic:"security" },
    { id:"fc11", front:"Was macht HttpOnly bei Cookies?", back:"Cookie ist NICHT via JavaScript (document.cookie) zugänglich → Schutz vor XSS.", topic:"cookies" },
    { id:"fc12", front:"Was macht SameSite=Strict?", back:"Cookie wird NUR bei Same-Site Requests gesendet → starker Schutz gegen CSRF.", topic:"cookies" },
    { id:"fc13", front:"Was ist JWT?", back:"JSON Web Token — tokenbasierte Authentifizierung. Aufbau: Header.Payload.Signature (Base64). Signiert, NICHT verschlüsselt.", topic:"jwt" },
    { id:"fc14", front:"JWT Signatur berechnen?", back:"HMACSHA256(Base64(Header) + '.' + Base64(Payload), secret)", topic:"jwt" },
    { id:"fc15", front:"Arrow Function vs reguläre Funktion?", back:"Arrow Function hat KEIN eigenes this — erbt this vom umgebenden lexikalischen Scope. Reguläre Funktion: eigenes this (Aufrufkontext).", topic:"closures" },
    { id:"fc16", front:"Was sind Vue.js Lifecycle Hooks?", back:"Funktionen die zu bestimmten Zeitpunkten im Vue-Lebenszyklus aufgerufen werden (created, mounted, unmounted…).", topic:"vue" },
    { id:"fc17", front:"created vs mounted in Vue?", back:"created: Instanz erstellt, DOM noch nicht verfügbar. mounted: Instanz an DOM angehängt, DOM-Zugriff möglich.", topic:"vue" },
    { id:"fc18", front:"Was ist MVVM?", back:"Model (Daten) – View (HTML/UI) – ViewModel (verbindet beides über Bindings). Vue.js folgt diesem Pattern.", topic:"vue" },
    { id:"fc19", front:"v-model in Vue?", back:"Two-Way Data Binding — Änderungen im Input aktualisieren die Daten und umgekehrt.", topic:"vue" },
    { id:"fc20", front:"Session Cookie vs Persistent Cookie?", back:"Session: kein Max-Age, gelöscht bei Browser-Schließung. Persistent: hat Max-Age/Expires, bleibt gespeichert.", topic:"cookies" },
    { id:"fc21", front:"Prototypenbasierte Vererbung?", back:"Objekte erben direkt von anderen Objekten über die Prototype Chain. ES6-Klassen sind syntaktischer Zucker darüber.", topic:"oop" },
    { id:"fc22", front:"Was macht express.static()?", back:"Stellt statische Dateien (HTML, CSS, JS, Bilder) aus einem Verzeichnis bereit: app.use(express.static('public'))", topic:"rest-express" },
    { id:"fc23", front:"Monolith vs SOA?", back:"Monolith: alles in einem Prozess (einfach, aber schwer skalierbar). SOA: unabhängige Services (skalierbar, unabhängiges Deployment).", topic:"architekturen" },
    { id:"fc24", front:"Was ist AJAX?", back:"Asynchronous JavaScript and XML — Daten vom Server laden ohne kompletten Page Reload. Heute meist via fetch().", topic:"vue" },
    { id:"fc25", front:"Symmetrische vs asymmetrische Verschlüsselung?", back:"Symmetrisch: gleicher Key für beides (AES, schnell). Asymmetrisch: Public Key verschlüsselt, Private Key entschlüsselt (RSA, langsam).", topic:"https" },
    { id:"fc26", front:"Was ist ein CSR (Certificate Signing Request)?", back:"Wird mit dem eigenen Private Key erstellt und an eine CA gesendet, um ein signiertes Zertifikat zu erhalten.", topic:"https" },
    { id:"fc27", front:"Was ist MongoDB?", back:"Dokumentenorientierte NoSQL-Datenbank. Speichert Daten als flexible BSON-Dokumente (ähnlich JSON).", topic:"mongodb" },
    { id:"fc28", front:"MongoDB CRUD-Operationen?", back:"insertOne, find, updateOne, deleteOne", topic:"mongodb" },
    { id:"fc29", front:"Was ist const in JS?", back:"Block Scope. Referenz unveränderbar — bei Objekten kann der INHALT aber geändert werden!", topic:"js-es6" },
    { id:"fc30", front:"Was macht der Garbage Collector?", back:"Erkennt unerreichbare Objekte (keine Referenzen mehr) und gibt deren Speicher automatisch frei.", topic:"js-es6" },
    { id:"fc31", front:"Was ist ein Promise?", back:"Repräsentiert einen zukünftigen Wert. Zustände: pending → fulfilled (resolve) oder rejected (reject).", topic:"promises" },
    { id:"fc32", front:"Wie wird JWT im HTTP-Header gesendet?", back:"Authorization: Bearer <token>", topic:"jwt" },
    { id:"fc33", front:"Hoisting in JavaScript?", back:"var-Deklarationen werden an den Anfang des Function Scope gehoben. Wert ist bis zur Zuweisung undefined. let/const werden nicht gehoben.", topic:"scopes" },
    { id:"fc34", front:"TLS kombiniert welche Verschlüsselung?", back:"Asymmetrisch für den Handshake (Key Exchange) + Symmetrisch für die eigentliche Datenübertragung.", topic:"https" },
    { id:"fc35", front:"Bootstrap Grid — wie viele Spalten?", back:"12-Spalten System. col-12 = volle Breite. col-lg-4 = 1/3 ab Breakpoint lg.", topic:"bootstrap" }
];

const QUIZ_QUESTIONS = [
    { id:"qz1", question:"Welchen Scope hat `var`?", options:["Block Scope","Function Scope","Modul Scope","Keinen Scope"], correct:1, explanation:"var hat Function Scope und wird gehoben (Hoisting)." },
    { id:"qz2", question:"`const obj = {}; obj.name = 'test';` — was passiert?", options:["TypeError","Funktioniert — Inhalt kann geändert werden","obj wird undefined","SyntaxError"], correct:1, explanation:"const macht die Referenz unveränderbar, nicht den Inhalt des Objekts." },
    { id:"qz3", question:"JavaScript ist…", options:["Multi-threaded","Single-threaded mit Event Loop","Parallel","Immer synchron"], correct:1, explanation:"JS hat einen Call Stack. Der Event Loop ermöglicht nicht-blockierendes IO." },
    { id:"qz4", question:"HTTP-Statuscode 401 bedeutet…", options:["Forbidden","Not Found","Unauthorized","Bad Request"], correct:2, explanation:"401 = Unauthorized (keine/ungültige Authentifizierung). 403 = Forbidden (authentifiziert, aber nicht berechtigt)." },
    { id:"qz5", question:"CORS steht für…", options:["Cross-Origin Request Security","Cross-Origin Resource Sharing","Client-Origin Response System","Cross-Object Resource Standard"], correct:1, explanation:"CORS erlaubt kontrollierte Cross-Origin-Zugriffe über HTTP-Header." },
    { id:"qz6", question:"Welches Cookie-Attribut schützt vor XSS?", options:["Secure","SameSite","HttpOnly","Path"], correct:2, explanation:"HttpOnly verhindert JavaScript-Zugriff auf das Cookie (document.cookie)." },
    { id:"qz7", question:"JWT ist…", options:["Verschlüsselt","Signiert aber nicht verschlüsselt","Weder signiert noch verschlüsselt","Nur Base64-encoded"], correct:1, explanation:"JWT ist signiert (Integrität prüfbar), aber der Inhalt ist nur Base64-encoded, nicht verschlüsselt." },
    { id:"qz8", question:"Was macht `super()` in einer ES6-Klasse?", options:["Ruft Garbage Collector auf","Erstellt neue Instanz","Ruft Konstruktor der Elternklasse auf","Exportiert die Klasse"], correct:2, explanation:"super() ruft den constructor() der Elternklasse auf und muss in abgeleiteten Klassen vor this verwendet werden." },
    { id:"qz9", question:"Hauptvorteil von SOA gegenüber Monolith?", options:["Einfacheres Deployment","Weniger Code","Unabhängige Skalierbarkeit","Schnellere Ausführung"], correct:2, explanation:"SOA erlaubt unabhängiges Skalieren, Deployen und verschiedene Technologien pro Service." },
    { id:"qz10", question:"Welches Vue-Directive ermöglicht Two-Way-Binding?", options:["v-bind","v-for","v-model","v-if"], correct:2, explanation:"v-model verbindet Input-Felder bidirektional mit den Daten (Two-Way Data Binding)." },
    { id:"qz11", question:"REST steht für…", options:["Remote Execution Standard Transfer","Representational State Transfer","Request-Event-Service Technology","Realtime Endpoint Service"], correct:1, explanation:"Representational State Transfer — Architekturstil für verteilte Systeme." },
    { id:"qz12", question:"Prepared Statements schützen vor…", options:["XSS","CSRF","SQL-Injection","Man-in-the-Middle"], correct:2, explanation:"Prepared Statements trennen SQL-Code von Daten und verhindern SQL-Injection." },
    { id:"qz13", question:"Arrow Functions in JavaScript…", options:["Haben eigenes this","Erben this vom umgebenden Scope","Haben kein return","Können keine Callbacks sein"], correct:1, explanation:"Arrow Functions haben kein eigenes this — sie erben es lexikalisch vom umgebenden Scope." },
    { id:"qz14", question:"Eine Closure ist…", options:["Eine verschlüsselte Variable","Innere Funktion die auf äußere Variablen zugreift","Ein geschlossenes Modul","Eine Klasse ohne Konstruktor"], correct:1, explanation:"Eine Closure 'schließt' die Variablen der äußeren Funktion ein und behält Zugriff darauf." },
    { id:"qz15", question:"MongoDB speichert Daten als…", options:["Tabellen","BSON-Dokumente","XML-Dateien","CSV-Zeilen"], correct:1, explanation:"MongoDB ist dokumentenorientiert und speichert Daten als BSON (Binary JSON)." },
    { id:"qz16", question:"TLS kombiniert…", options:["Nur symmetrische Verschlüsselung","Nur asymmetrische Verschlüsselung","Asymmetrisch für Handshake + Symmetrisch für Daten","Keine Verschlüsselung"], correct:2, explanation:"TLS nutzt asymmetrische Crypto für den sicheren Key-Exchange, dann symmetrische für die schnelle Datenübertragung." },
    { id:"qz17", question:"SameSite=Strict bei Cookies bewirkt…", options:["Nur über HTTPS gesendet","Nur bei Same-Site Requests gesendet","Nicht via JS zugänglich","Cookie wird sofort gelöscht"], correct:1, explanation:"SameSite=Strict verhindert das Senden bei Cross-Site Requests → CSRF-Schutz." },
    { id:"qz18", question:"Session Cookie vs Persistent Cookie?", options:["Kein Unterschied","Session hat Max-Age","Session wird bei Browser-Schließung gelöscht","Persistent ist sicherer"], correct:2, explanation:"Session Cookies haben kein Max-Age/Expires und werden bei Browser-Schließung gelöscht." },
    { id:"qz19", question:"JWT wird im HTTP-Header gesendet als…", options:["Cookie: Bearer token","Authorization: Bearer <token>","X-JWT: <token>","Content-Type: jwt"], correct:1, explanation:"JWT wird im Authorization-Header mit dem Bearer-Schema gesendet." },
    { id:"qz20", question:"Hoisting in JavaScript betrifft…", options:["let und const","Nur Arrow Functions","var-Deklarationen (werden an Scope-Anfang gehoben)","Alle Variablen gleich"], correct:2, explanation:"var-Deklarationen werden gehoben (Wert = undefined bis Zuweisung). let/const werden nicht gehoben (Temporal Dead Zone)." }
];

const LEARNING_PLAN = [
    { day:1, focus:"JS: var/let/const, Scopes, Speicher, Closures", topics:["js-es6","scopes","closures"] },
    { day:2, focus:"OOP, Promises, Event Loop, async/await", topics:["oop","async","promises"] },
    { day:3, focus:"Node.js, Module, REST & Express.js", topics:["node","modules","rest-express"] },
    { day:4, focus:"HTTP, CORS, Architekturen (Monolith/SOA)", topics:["http","cors","architekturen"] },
    { day:5, focus:"Vue.js, AJAX, Bootstrap", topics:["vue","bootstrap"] },
    { day:6, focus:"Cookies, JWT, Sessions", topics:["cookies","jwt"] },
    { day:7, focus:"Security, HTTPS, MongoDB & Generalprobe", topics:["security","https","mongodb","tools"] }
];

const CHEATSHEET = [
    { title:"var / let / const", icon:"fa-brands fa-js",
      content:'<div class="space-y-1.5 text-sm"><div class="flex gap-3"><code class="text-emerald-600 w-12 font-bold">var</code><span>Function Scope · Hoisting</span></div><div class="flex gap-3"><code class="text-emerald-600 w-12 font-bold">let</code><span>Block Scope · reassignable</span></div><div class="flex gap-3"><code class="text-emerald-600 w-12 font-bold">const</code><span>Block Scope · Referenz fix</span></div></div>' },
    { title:"REST & HTTP", icon:"fa-solid fa-exchange-alt",
      content:'<div class="grid grid-cols-2 gap-1.5 text-sm"><div><b class="text-emerald-600">GET</b> Read</div><div><b class="text-emerald-600">POST</b> Create</div><div><b class="text-emerald-600">PUT</b> Update</div><div><b class="text-emerald-600">DELETE</b> Delete</div></div><div class="mt-2 text-xs bg-emerald-50 p-2 rounded-lg text-emerald-700">Stateless · Uniform Interface · URIs · JSON</div>' },
    { title:"HTTP Statuscodes", icon:"fa-solid fa-signal",
      content:'<div class="text-xs space-y-1"><div><b class="text-emerald-600">200</b> OK · <b>201</b> Created</div><div><b class="text-amber-600">301</b> Moved · <b>304</b> Not Modified</div><div><b class="text-red-500">400</b> Bad Req · <b>401</b> Unauth · <b>403</b> Forbidden · <b>404</b> Not Found</div><div><b class="text-red-500">500</b> Internal Server Error</div></div>' },
    { title:"Cookies", icon:"fa-solid fa-cookie-bite",
      content:'<div class="text-xs space-y-1"><div>Server: <code class="bg-slate-100 px-1 rounded">Set-Cookie: name=wert</code></div><div>Client: <code class="bg-slate-100 px-1 rounded">Cookie: name=wert</code></div><div class="grid grid-cols-2 gap-1 pt-1"><div><b>HttpOnly</b> kein JS</div><div><b>Secure</b> HTTPS</div><div><b>SameSite</b> CSRF</div><div><b>Max-Age</b> Persistenz</div></div></div>' },
    { title:"JWT Aufbau", icon:"fa-solid fa-key",
      content:'<div class="text-xs space-y-1.5"><code class="block bg-slate-100 px-2 py-1 rounded">xxxxx.yyyyy.zzzzz</code><div><b>Header</b> (B64): Typ+Algo</div><div><b>Payload</b> (B64): Claims</div><div><b>Signature</b>: HMAC(H.P, secret)</div><div class="text-amber-700 bg-amber-50 p-1.5 rounded">Signiert ≠ verschlüsselt!</div></div>' },
    { title:"Web-Security", icon:"fa-solid fa-shield-halved",
      content:'<div class="text-xs space-y-1.5"><div><b>SQLi</b> → Prepared Statements</div><div><b>XSS</b> → Escaping + CSP</div><div><b>CSRF</b> → SameSite + Token</div><div><b>HTTPS</b> → TLS</div></div>' },
    { title:"Event Loop", icon:"fa-solid fa-sync",
      content:'<div class="text-sm">Call Stack → Web APIs → Callback Queue → Event Loop<br><span class="text-xs">Single-Threaded · IO an OS · CPU-Tasks blockieren!</span></div>' },
    { title:"Verschlüsselung", icon:"fa-solid fa-lock",
      content:'<div class="text-xs space-y-1"><div><b>Symmetrisch:</b> gleicher Key (AES) — schnell</div><div><b>Asymmetrisch:</b> Pub/Priv Key (RSA) — langsam</div><div><b>TLS:</b> Asymm. Handshake + Symm. Daten</div><div>CSR → CA → Zertifikat</div></div>' },
    { title:"Vue.js & MVVM", icon:"fa-brands fa-vuejs",
      content:'<div class="text-xs space-y-1"><div><b>M</b>odel · <b>V</b>iew · <b>V</b>iew<b>M</b>odel</div><div>v-model (2-Way) · v-bind (1-Way)</div><div>v-if · v-show · v-for</div><div>Hooks: created · mounted · unmounted</div></div>' },
    { title:"MongoDB", icon:"fa-solid fa-database",
      content:'<div class="text-xs space-y-1"><div>Dokumentenorientiert (BSON)</div><div><code>insertOne · find · updateOne · deleteOne</code></div><div>SQL: Relational/ACID · NoSQL: Schemafrei/BASE</div></div>' },
    { title:"Bootstrap Grid", icon:"fa-brands fa-bootstrap",
      content:'<div class="text-xs space-y-1"><div>12-Spalten: col-12 = 100%</div><div>Responsive: col-sm · col-md · col-lg · col-xl</div><div>Container → Row → Col</div></div>' },
    { title:"Express.js", icon:"fa-solid fa-server",
      content:'<div class="text-xs font-mono space-y-0.5"><div>const app = express();</div><div>app.get(\'/path\', (req, res) => {});</div><div>app.use(middleware);</div><div>app.listen(3000);</div></div>' }
];
